namespace SimpleBroker
{
    /// <summary>
    /// Record representing the commissions generated by an execution
    /// </summary>
    public record CommissionReport
    {
        /// <summary>
        /// The execution's id this commission belongs to.
        /// </summary>
        public required string ExecId { get; init; }

        /// <summary>
        /// The commissions cost.
        /// </summary>
        public double Commission { get; init; }

        /// <summary>
        /// The reporting currency.
        /// </summary>
        public required string Currency { get; init; }

        /// <summary>
        /// The realized profit and loss
        /// </summary>
        public double RealizedPNL { get; init; }

        /// <summary>
        /// The income return.
        /// </summary>
        public double Yield { get; init; }

        /// <summary>
        /// Yield redemption date.
        /// </summary>
        public DateOnly YieldRedemptionDate { get; init; }
    }
}
