namespace IBKRWrapper.Constants
{
    public enum GenericTickIds
    {
        Low13Weeks = 15,
        High13Weeks = 16,
        Low26Weeks = 17,
        High26Weeks = 18,
        Low52Weeks = 19,
        High52Weeks = 20,
        AverageVolume = 21,
        OptionHistoricalVol = 23,
        OptionImpliedVol = 24,
        OptionCallOpenInterest = 27,
        OptionPutOpenInterest = 28,
        OptionCallVolume = 29,
        OptionPutVolume = 30,
        IndexFuturePremium = 31,
        AuctionVolume = 34,
        AuctionPrice = 35,
        AuctionImbalance = 36,
        MarkPrice = 37,
        Shortable = 46,
        TimeAndSales = 47,
        TradeCount = 54,
        TradeRate = 55,
        VolumeRate = 56,
        LastRthTrade = 57,
        RtHistoricalVol = 58,
        IbDividends = 59,
        BondFactorMultiplier = 60,
        RegulatoryImbalance = 61,
        News = 62,
        Volume3Minutes = 63,
        Volume5Minutes = 64,
        Volume10Minutes = 65,
        RtTradeVolume = 77,
        CreditmanSlowMarkPrice = 79,
        FuturesOpenInterest = 86,
        AverageOptionVolume = 87,
        ShortableShares = 89,
        EtfNavClose = 92,
        EtfNavPriorClose = 93,
        EtfNavBid = 94,
        EtfNavAsk = 95,
        EtfNavLast = 96,
        EtfNavFrozenLast = 97,
        EtfNavHigh = 98,
        EtfNavLow = 99,
        EstimatedIpoMidpoint = 101,
        FinalIpoPrice = 102,
    }
}
